name: ProGames
version: '1.0'
main: net.cjsmc.progames.ProGames
api-version: '1.21'
load: STARTUP
authors: [ CJSGamer ]
description: Progames is a 1.21 minecraft plugin by CJSGamer
commands:
  example:
    description: An example command